### ISSUE TITLE
No video on Sony and Axis ipcam

### ISSUE THREAD

**Issue by fabioz23** [xsmart/ve#8]
Hi,

I'm testing vdceye on a mix of camera set, Dahua and Hikvision cameras works ok, the video starts after onvif scan.
The problem is related to Sony and Axis cameras, it found the cameras but no video if I drag the camera on the matrix.

How can I fix this?

**Comment by xsmart** [comment]
For the sony and Axis cameras, the problem maybe is onvif auth failed. 
1. Make the camera and vdceye machine same time(you can use NTP)
2. For Axis, disable the onvif advanced  auth option in the service page.

**Comment by fabioz23** [comment]
I’ve set the correct time but vdcEye still not catch video from camera.




Il giorno 12/gen/2015, alle ore 13:39, xsmart <notifications@github.com> ha scritto:

**Comment by fabioz23** [comment]
![vdceye](https://cloud.githubusercontent.com/assets/729310/5703450/ec2a348c-9a66-11e4-8c82-0e7292d82abf.jpg)

**Comment by xsmart** [comment]
can i remote you desktop for axis camera ?

**Comment by xsmart** [comment]
Use Teamviewer or QQ?

**Comment by fabioz23** [comment]
give your email, I’ll send you the details…..


Il giorno 12/gen/2015, alle ore 14:41, xsmart <notifications@github.com> ha scritto:

**Comment by xsmart** [comment]
xsmart@vdceye.com

**Comment by xsmart** [comment]
For Axis 
System Options
	Advanced
		Plain Config
		Webservice(Select Group)
			Disable the Enable replay attack protection

**Comment by xsmart** [comment]
close it if has no issue
